### PR TITLE
remove deprecated function, onAttach(Activity), and move create rende…

### PR DESCRIPTION
**Pull request by wangchauyan**
remove deprecated function - onAttach (Activity activity), should not use a deprecated function in code. 

move create pdf render / show page functions to onStart

### CODE REVIEW

**Comment by wangchauyan** [comment]
I signed it!

**Comment by yaraki** [comment]
Thanks, Chauyan. I'm merging this through our internal repository. It will be applied to GitHub as well.

**Comment by wangchauyan** [comment]
@yaraki  Thanks a lot.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Pull request closed without merging**
